name: Docker Build and Deploy craftapp_user_backend

on:
  push:
    branches:
      - master
      - preprod
  pull_request:
    branches:
      - master
      - preprod

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the Docker image based on the branch
      - name: Build Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            docker build -t bitlinksai/craftapp_user_backend:prod .
          elif [ "${{ github.ref }}" == "refs/heads/preprod" ]; then
            docker build -t bitlinksai/craftapp_user_backend:preprod .
          fi
          docker images  # List all images to verify the build

      # Stop and remove the previous container (if running)
      - name: Stop and remove previous container
        run: |
          docker stop craftapp_user_backend_prod || true
          docker rm craftapp_user_backend_prod || true
          docker stop craftapp_user_backend_preprod || true
          docker rm craftapp_user_backend_preprod || true

      # Remove previous Docker images
      - name: Remove previous Docker images
        run: |
          docker rmi bitlinksai/craftapp_user_backend:prod || true
          docker rmi bitlinksai/craftapp_user_backend:preprod || true

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            docker images  # List images to verify the prod image exists
            docker push bitlinksai/craftapp_user_backend:prod
          elif [ "${{ github.ref }}" == "refs/heads/preprod" ]; then
            docker images  # List images to verify the preprod image exists
            docker push bitlinksai/craftapp_user_backend:preprod
          fi

      # Run the Docker container
      - name: Run Docker container
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            docker run -d --name craftapp_user_backend_prod -p 8081:3000 --restart always bitlinksai/craftapp_user_backend:prod
          elif [ "${{ github.ref }}" == "refs/heads/preprod" ]; then
            docker run -d --name craftapp_user_backend_preprod -p 8081:3000 --restart always bitlinksai/craftapp_user_backend:preprod
          fi